Repository icefoganalytics/travel-authorization, pull requests merged in 2024-07, with the labels that each got.

#202 Frontend to Backend auth design doc
  _Design/Flow Chart, Frontend to Backend Authentication.png
Labels: documentation

#204 Fixup: Unbreak Travel Desk Again
  _Design/Entity Relationship Diagram.png
  _Design/Entity Relationship Diagram.wsd
  _Design/User Stories, Travel Desk, 2024-01-24.docx
  _Design/WireFrame, TravelDesk, 2024-01-24.pdf
  api/src/db/migrations/20240718003057_standardize-travel-desk-question-table.ts
  api/src/db/migrations/20240718011154_standardize-travel-desk-question-types.ts
  api/src/initializers/20-run-migrations.ts
  api/src/models/index.ts
  api/src/models/travel-desk-question.ts
  api/src/models/travel-desk-travel-request.ts
  api/src/routes/traveldesk-router.ts
  api/tests/factories/travel-authorization-factory.ts
  bin/dev
  bin/github_api.rb
  package-lock.json
  package.json
  web/src/api/travel-desk-questions-api.js
  web/src/components/travel-desk-travel-requests/TravelDeskTravelRequestEditCard.vue
  web/src/locales/en.js
  web/src/modules/preapproved/views/Preapproved.vue
  web/src/modules/travel-authorizations/components/my-travel-authorizations-table/SubmitTravelDeskRequestButton.vue
  web/src/modules/travel-authorizations/layouts/MyTravelAuthorizationLayout.vue
  web/src/modules/travel-authorizations/pages/README.md
  web/src/modules/travel-authorizations/router.js
  web/src/modules/travelDesk/views/Common/PrintTravelDeskReport.vue
  web/src/modules/travelDesk/views/Desk/Components/FlightSegmentsTable.vue
  web/src/modules/travelDesk/views/Desk/Components/NewQuestion.vue
  web/src/modules/travelDesk/views/Desk/Components/QuestionsTable.vue
  web/src/modules/travelDesk/views/Desk/ProcessTravelDeskRequest.vue
  web/src/modules/travelDesk/views/Desk/TravelDeskRequests.vue
  web/src/modules/travelDesk/views/Requests/NewTravelDeskRequest.vue
  web/src/modules/travelDesk/views/TravelDesk.vue
  web/src/pages/README.md
  web/src/pages/my-travel-requests/request/RequestEditPage.vue
  web/src/pages/my-travel-requests/request/RequestPage.vue
Labels: bug

#205 Fixup: Auth0 Production Config
  web/src/config.js
Labels: bug

#206 Fixup: Fix Some Travel Desk Bugs
  api/src/controllers/travel-desk-flight-requests-controller.ts
  api/src/controllers/travel-desk-hotels-controller.ts
  api/src/controllers/travel-desk-other-transportations-controller.ts
  api/src/controllers/travel-desk-rental-cars-controller.ts
  api/src/services/travel-authorizations/approve-service.ts
  web/src/components/travel-desk-flight-requests/TravelDeskFlightRequestsEditTable.vue
  web/src/components/travel-desk-hotels/TravelDeskHotelEditTable.vue
  web/src/components/travel-desk-other-transportations/TravelDeskOtherTransportationEditTable.vue
  web/src/components/travel-desk-rental-cars/TravelDeskRentalCarsEditTable.vue
Labels: bug

#200 Build UI Travel Desk Request "submitted" State in Travel -> Request Tab
  web/package-lock.json
  web/package.json
  web/src/components/travel-desk-flight-requests/TravelDeskFlightRequestCreateDialog.vue
  web/src/components/travel-desk-flight-requests/TravelDeskFlightRequestEditDialog.vue
  web/src/components/travel-desk-flight-requests/TravelDeskFlightRequestsTable.vue
  web/src/components/travel-desk-hotels/TravelDeskHotelCreateDialog.vue
  web/src/components/travel-desk-hotels/TravelDeskHotelEditDialog.vue
  web/src/components/travel-desk-hotels/TravelDeskHotelsEditTable.vue
  web/src/components/travel-desk-hotels/TravelDeskHotelsTable.vue
  web/src/components/travel-desk-other-transportations/TravelDeskOtherTransportationCreateDialog.vue
  web/src/components/travel-desk-other-transportations/TravelDeskOtherTransportationEditDialog.vue
  web/src/components/travel-desk-other-transportations/TravelDeskOtherTransportationsEditTable.vue
  web/src/components/travel-desk-other-transportations/TravelDeskOtherTransportationsTable.vue
  web/src/components/travel-desk-rental-cars/TravelDeskRentalCarsEditTable.vue
  web/src/components/travel-desk-rental-cars/TravelDeskRentalCarsTable.vue
  web/src/components/travel-desk-travel-requests/TravelDeskTravelRequestCard.vue
  web/src/components/travel-desk-travel-requests/TravelDeskTravelRequestEditCard.vue
  web/src/components/travel-desk-travel-requests/TravelerDetailsCard.vue
  web/src/components/travel-desk-travel-requests/TravelerDetailsFormCard.vue
  web/src/components/travel-request-rental-cars/TravelDeskRentalCarCreateDialog.vue
  web/src/components/travel-request-rental-cars/TravelDeskRentalCarEditDialog.vue
  web/src/modules/travelDesk/views/Common/TitleCard.vue
  web/src/modules/travelDesk/views/Desk/Components/FlightOptionsTable.vue
  web/src/modules/travelDesk/views/Desk/Components/FlightSegmentsTable.vue
  web/src/modules/travelDesk/views/Desk/Components/NewQuestion.vue
  web/src/modules/travelDesk/views/Desk/Components/QuestionsTable.vue
  web/src/modules/travelDesk/views/Desk/Components/TravelPortModal.vue
  web/src/modules/travelDesk/views/Desk/ProcessTravelDeskRequest.vue
  web/src/modules/travelDesk/views/Requests/Components/ItineraryModal.vue
  web/src/modules/travelDesk/views/Requests/Components/TravelerDetails.vue
  web/src/modules/travelDesk/views/Requests/NewTravelDeskRequest.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/HotelRequestTable.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/NewFlightRequest.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/NewHotelRequest.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/NewRentalCarRequest.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/NewTransportationRequest.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/RentalCarRequestTable.vue
  web/src/modules/travelDesk/views/Requests/RequestDialogs/TransportationRequestTable.vue
  web/src/pages/my-travel-requests/request/RequestPage.vue
Labels: enhancement

#203 Issue 194/make sure users dont get created twice
  .gitignore
  .tool-versions
  api/package-lock.json
  api/package.json
  api/src/integrations/auth0-integration.ts
  api/src/integrations/index.ts
  api/src/middleware/authorization-middleware.ts
  api/src/middleware/authz.middleware.ts
  api/src/middleware/index.ts
  api/src/middleware/jwt-middleware.ts
  api/src/routes/index.ts
  api/tests/controllers/expenses-controller.test.ts
  api/tests/controllers/travel-authorizations/estimates/generate-controller.test.ts
  api/tests/middleware/authorization-middleware.test.ts
  api/tests/support/mock-current-user.ts
Labels: bug, documentation, enhancement, help wanted, refactor, :lock: security

#207 Ytgov: Issue 82: Data Modeling for Admin Tables for Travel Rates
  _Design/Entity Relationship Diagram.png
  _Design/Entity Relationship Diagram.wsd
  api/src/db/data/per-diems.csv
  api/src/db/migrations/20240719232927_standardize-per-diem-table.ts
  api/src/db/migrations/20240722162530_standardize-per-diem-claim-types.ts
  api/src/db/migrations/20240722171542_add-travel-allowances-table.ts
  api/src/db/seeds/050_per-diem-seeds.ts
  api/src/db/seeds/060_travel-allowances-seeds.ts
  api/src/initializers/20-run-migrations.ts
  api/src/models/index.ts
  api/src/models/per-diem.ts
  api/src/models/travel-allowance.ts
  api/src/services/estimates/bulk-generate-service.ts
  api/src/services/per-diems-service.ts
  api/tests/factories/index.ts
  api/tests/factories/per-diem-factory.ts
  api/tests/factories/travel-allowance-factory.ts
  api/tests/services/estimates/bulk-generate-service.test.ts
  docker-compose.development.yml
Labels: enhancement

#211 Update node version
  Dockerfile
  api/development.Dockerfile
  api/package-lock.json
  api/package.json
  docker-compose.development.yml
  docker-compose.yml
  web/development.Dockerfile
  web/package-lock.json
  web/package.json
Labels: enhancement, refactor

#212 Make Seeding Non-Destructive
  Dockerfile
  _Design/Entity Relationship Diagram.png
  _Design/Entity Relationship Diagram.wsd
  api/package.json
  api/src/db/data/travel-authorization-pre-approval-profiles.csv
  api/src/db/data/travel-authorization-pre-approvals.csv
  api/src/db/migrations/20240729234853_standardize-roles-table.ts
  api/src/db/migrations/20240730164117_standardize-role-names.ts
  api/src/db/seeds/010_base-seeds.ts
  api/src/db/seeds/010_user-seeds.ts
  api/src/db/seeds/020_locations-seeds.ts
  api/src/db/seeds/030_travel-authorization-pre-approvals-seeds.ts
  api/src/db/seeds/040_lots-of-legacy-seeds.ts
  api/src/db/seeds/040_travel-authorization-seeds.ts
  api/src/db/seeds/045_distance-matrix-seeds.ts
  api/src/db/seeds/050_per-diem-seeds.ts
  api/src/db/seeds/data/distance-matrix.csv
  api/src/db/seeds/data/locations.csv
  api/src/db/seeds/data/per-diems.csv
  api/src/middleware/index.ts
  api/src/models/index.ts
  api/src/models/role.ts
  api/src/models/user.ts
  api/src/routes/users-router.ts
  api/src/services/security.ts
  api/src/services/users/create-service.ts
  api/src/services/users/ensure-service.ts
  api/src/services/yk-government-directory-sync-service.ts
  bin/dev
  web/src/api/users-api.js
  web/src/components/Administration/UserManagement/UserComponent/Form.vue
  web/src/filters/index.js
  web/src/locales/en.js
  web/src/pages/UserProfilePage.vue
Labels: bug

#213 Clean up Adminstration Users and User Edit Pages
  api/src/routes/lookup-router.ts
  api/src/routes/users-router.ts
  web/src/components/Administration/UserManagement/UserComponent/Form _old.vue
  web/src/pages/AdministrationPage.vue
  web/src/pages/administration/UsersPage.vue
  web/src/pages/administration/users/UserEditPage.vue
  web/src/router.js
  web/src/use/use-breadcrumbs.js
Labels: bug, refactor
