Repository icefoganalytics/travel-authorization, pull requests merged in 2024-09, with the labels that each got.

#209 Switch test site from jest to vitest
  api/bin/boot-app.sh
  api/jest.config.ts
  api/package-lock.json
  api/package.json
  api/src/db/db-client.ts
  api/src/db/utils/monkey-patch-sequelize-errors-for-jest.ts
  api/src/initializers/index.ts
  api/tests/README.md
  api/tests/controllers/expenses-controller.test.ts
  api/tests/controllers/travel-authorizations/estimates/generate-controller.test.ts
  api/tests/global-setup.ts
  api/tests/middleware/authorization-middleware.test.ts
  api/tests/models/general-ledger-coding.test.ts
  api/tests/services/travel-authorizations/approve-service.test.ts
  api/tests/services/travel-authorizations/create-service.test.ts
  api/tests/setup.ts
  api/tests/support/index.ts
  api/tests/support/mock-current-user.ts
  api/tests/support/request.ts
  api/tests/tsconfig.json
  api/tsconfig.json
  api/vite.config.mts
  bin/dev
  docker-compose.development.yml
Labels: enhancement, refactor

#216 Fixup: Broken Types After TypeScript Config Changes
  api/src/controllers/base-controller.ts
  api/src/controllers/expenses/upload-controller.ts
  api/src/middleware/authorization-middleware.ts
  api/src/middleware/index.ts
  api/src/routes/form-router.ts
  api/src/routes/preapproved-router.ts
  api/src/routes/reconcile-router.ts
  api/src/routes/traveldesk-router.ts
  api/src/routes/users-router.ts
  api/src/services/expenses/upload-service.ts
Labels: bug

#217 Unable to Add Agent
  .vscode/settings.json
  _Design/Entity Relationship Diagram.png
  _Design/Entity Relationship Diagram.wsd
  api/src/controllers/index.ts
  api/src/controllers/travel-desk-travel-agencies-controller.ts
  api/src/db/migrations/20240919231332_rename-travel-desk-agent-table-to-travel-desk-agencies-table.ts
  api/src/db/migrations/20240920234852_add-new-columns-to-travel-desk-travel-agencies-table.ts
  api/src/middleware/index.ts
  api/src/models/index.ts
  api/src/models/role.ts
  api/src/models/travel-desk-travel-agency.ts
  api/src/models/travel-desk-travel-agent.ts
  api/src/models/travel-desk-travel-request.ts
  api/src/models/user.ts
  api/src/policies/index.ts
  api/src/policies/travel-desk-travel-agencies-policy.ts
  api/src/policies/travel-desk-travel-requests-policy.ts
  api/src/routes/index.ts
  api/src/routes/traveldesk-router.ts
  api/src/services/index.ts
  api/src/services/travel-desk-travel-agencies/create-service.ts
  api/src/services/travel-desk-travel-agencies/index.ts
  api/src/services/travel-desk-travel-agencies/update-service.ts
  bin/dev
  web/package-lock.json
  web/package.json
  web/src/api/travel-desk-travel-agencies-api.js
  web/src/components/Administration/LookupTableManagement/TravelAgents.vue
  web/src/components/Administration/LookupTableManagement/TravelAgentsComponents/NewTravelAgent.vue
  web/src/components/travel-desk-travel-agencies/TravelDeskTravelAgencySelect.vue
  web/src/filters/index.js
  web/src/layouts/Layout.vue
  web/src/modules/preapproved/views/Requests/NewTravelRequest.vue
  web/src/modules/travelDesk/views/Desk/PnrDocument/UploadPnrModal.vue
  web/src/modules/travelDesk/views/Desk/ProcessTravelDeskRequest.vue
  web/src/pages/AdministrationPage.vue
  web/src/pages/administration/TravelAgenciesPage.vue
  web/src/pages/administration/travel-agencies/TravelAgencyEditPage.vue
  web/src/pages/administration/travel-agencies/TravelAgencyNewPage.vue
  web/src/router.js
  web/src/use/use-travel-desk-travel-agencies.js
  web/src/use/use-travel-desk-travel-agency.js
  web/src/utils/validators.js
  web/src/utils/validators/greater-than-or-equal-to-date.js
  web/src/utils/validators/index.js
  web/src/utils/validators/is-email.js
  web/src/utils/validators/is-general-ledger-code.js
  web/src/utils/validators/is-integer.js
  web/src/utils/validators/is-phone-number.js
  web/src/utils/validators/required.js
Labels: bug, refactor

#219 Ytgov Issue 89: Travel Auth Ability for Traveler To Update Form
  api/src/controllers/travel-authorizations/index.ts
  api/src/controllers/travel-authorizations/revert-to-draft-controller.ts
  api/src/policies/travel-authorizations/index.ts
  api/src/policies/travel-authorizations/revert-to-draft-policy.ts
  api/src/routes/index.ts
  api/src/services/travel-authorizations/index.ts
  api/src/services/travel-authorizations/revert-to-draft-service.ts
  web/src/api/travel-authorizations-api.js
  web/src/components/travel-authorizations/RevertToDraftButton.vue
  web/src/modules/travel-authorizations/pages/ReadMyTravelAuthorizationDetailsPage.vue
Labels: enhancement

#220 Ytgov Issue 90: Travel Auth Reassign a Supervisor/Approver
  api/package.json
  api/src/policies/travel-authorizations/submit-policy.ts
  api/src/services/travel-authorizations/submit-service.ts
  api/src/services/travel-authorizations/update-service.ts
  web/src/components/travel-authorizations/manange/ReAssignButtonDialog.vue
  web/src/components/users/UserEmailSearchableCombobox.vue
  web/src/modules/travel-authorizations/components/edit-my-travel-authorization-details-page/ApprovalsFormCard.vue
  web/src/modules/travel-authorizations/components/edit-my-travel-authorization-expense-page/RequestApprovalForm.vue
  web/src/modules/travel-authorizations/components/edit-travel-authorization-details-page/ApprovalsFormCard.vue
  web/src/modules/travel-authorizations/components/manage-travel-authorization-details-page/ManagementCard.vue
  web/src/modules/travel-authorizations/components/manage-travel-authorization-expense-page/ReassignApprovalForm.vue
  web/src/modules/travel-authorizations/components/manage-travel-authorizations-page/CreateTravelAuthorizationDialogButton.vue
  web/src/plugins/snack-plugin.js
Labels: enhancement
